spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 4545
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 8088

